spring:
  application:
    name: spring-datastar-examples
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  mvc:
    servlet:
      load-on-startup: 1

gg:
  jte:
    development-mode: true

server:
  port: 7331
